name: Greetings Workflow

on: [issues]
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          issue-message: "Congratz you created a new issue"